### PR TITLE
Update schema (Radio/Checkbox -> Choice/Multiplechoice)

### PR DESCRIPTION
**Pull request by czosel**
See https://github.com/projectcaluma/caluma/pull/238 and https://github.com/projectcaluma/caluma/pull/265

### CODE REVIEW

**Comment by czosel** [comment]
The removed `handleArchiveForm` and `handlePublishForm` are due to https://github.com/projectcaluma/caluma/pull/238.

A CHANGELOG would definitely start to make sense - probably in the caluma repo? /cc @sliverc

**Comment by kaldras** [comment]
Yeah, how about a main CHANGELOG in the caluma repo and the a link to it in the CHANGELOGS in the specific repos?

**Comment by kaldras** [comment]
And I would have done the `handleArchiveForm` and `handlePublishForm` in a own PR just so it is clear what was done. ;)

**Comment by czosel** [comment]
@kaldras Right, that would have been more clear. In https://github.com/projectcaluma/ember-caluma-form-builder/pull/209 I separated it in two different commits - separate PRs were a bit hard because you can't get the CI to run except with explicit pinning to the intermediate caluma version (the one containing only one of the breaking changes).

**Pull request merged**
